# Generated by Django 4.2 on 2023-04-12 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
    ]
